FROM python:3.8

WORKDIR /usr/src/app

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements.txt ./
RUN export DEBIAN_FRONTEND=noninteractive \
        && apt-get update \
        && python -m pip install --upgrade pip \
        && pip install --no-cache-dir -r requirements.txt
        
COPY . /usr/src/app
CMD [ "python", "./app.py"]